/* Bani names and grouping.
 *
 * The catalogue's own English field is a transliteration - "japujee saahib",
 * "shabadh hazaare paatishaahee 10" - which is faithful to the sounds but not
 * how anyone writes these names in English. This is the table of names as
 * they are actually written, so the list reads the way a reader expects.
 *
 * Groups: nitnem is the daily order; popular is everything else read as a
 * bani in its own right; vaar and raag are the browsing sections of Guru
 * Granth Sahib, kept apart so they do not bury the banis.
 */

export const BANI_INFO = {
  1: { name: "Gur Mantar", group: "nitnem" },
  2: { name: "Japji Sahib", group: "nitnem" },
  3: { name: "Shabad Hazare", group: "popular" },
  4: { name: "Jaap Sahib", group: "nitnem" },
  5: { name: "Shabad Hazare Patshahi 10", group: "popular" },
  6: { name: "Tav Prasad Savaiye (Sravag Sudh)", group: "nitnem" },
  7: { name: "Tav Prasad Savaiye (Deenan Ki)", group: "nitnem" },
  8: { name: "Akal Ustat Chaupai", group: "popular" },
  9: { name: "Benti Chaupai Sahib", group: "nitnem" },
  10: { name: "Anand Sahib", group: "nitnem" },
  11: { name: "Laavan", group: "popular" },
  12: { name: "Chandi Charitar", group: "popular" },
  13: { name: "Chandi di Vaar", group: "vaar" },
  14: { name: "Kuchaji", group: "popular" },
  15: { name: "Suchaji", group: "popular" },
  16: { name: "Gunvanti", group: "popular" },
  17: { name: "Phunhe Mahalla 5", group: "popular" },
  18: { name: "Chaubole", group: "popular" },
  19: { name: "Shastar Naam Mala", group: "popular" },
  21: { name: "Rehras Sahib", group: "nitnem" },
  22: { name: "Aarti", group: "popular" },
  23: { name: "Kirtan Sohila", group: "nitnem" },
  24: { name: "Ardas", group: "nitnem" },
  25: { name: "Sri Bhagauti Astotar (Panth Prakash)", group: "popular" },
  26: { name: "Sri Bhagauti Astotar (Sri Hazur Sahib)", group: "popular" },
  27: { name: "Barah Maha Manjh", group: "popular" },
  28: { name: "Barah Maha Savaiya", group: "popular" },
  29: { name: "Akal Ustat", group: "popular" },
  30: { name: "Salok Mahalla 9", group: "popular" },
  31: { name: "Sukhmani Sahib", group: "popular" },
  32: { name: "Sukhmana Sahib", group: "popular" },
  33: { name: "Bavan Akhri", group: "popular" },
  34: { name: "Sidh Gosht", group: "popular" },
  35: { name: "Dakhani Onkar", group: "popular" },
  36: { name: "Dukh Bhanjani Sahib", group: "popular" },
  38: { name: "Ragmala", group: "popular" },
  39: { name: "Bavan Akhri (Kabir Ji)", group: "popular" },
  40: { name: "Ghorian", group: "popular" },
  41: { name: "Karhale", group: "popular" },
  42: { name: "Birharhe", group: "popular" },
  43: { name: "Patti Likhi", group: "popular" },
  44: { name: "Patti Mahalla 3", group: "popular" },
  45: { name: "Ruti Mahalla 5", group: "popular" },
  46: { name: "Ramkali Sadd", group: "popular" },
  47: { name: "Thiti (Kabir Ji)", group: "popular" },
  48: { name: "Thiti Mahalla 1", group: "popular" },
  49: { name: "Thiti Mahalla 5", group: "popular" },
  50: { name: "Gauri Ki Vaar (Kabir Ji)", group: "vaar" },
  51: { name: "Bilaval Mahalla 3 Vaar Sat", group: "popular" },
  52: { name: "Vanjara", group: "popular" },
  53: { name: "Ugardanti", group: "popular" },
  55: { name: "Raag Sri Raag (Kabir Ji)", group: "raag" },
  56: { name: "Raag Gauri", group: "raag" },
  57: { name: "Raag Asa", group: "raag" },
  58: { name: "Raag Gujri", group: "raag" },
  59: { name: "Raag Sorath", group: "raag" },
  60: { name: "Raag Dhanasari", group: "raag" },
  61: { name: "Raag Jaitsri", group: "raag" },
  62: { name: "Raag Todi (Bhagat Bani)", group: "raag" },
  63: { name: "Raag Tilang (Bhagat Bani, Kabir Ji)", group: "raag" },
  64: { name: "Raag Suhi", group: "raag" },
  65: { name: "Raag Bilaval", group: "raag" },
  66: { name: "Raag Gond", group: "raag" },
  67: { name: "Raag Ramkali (Sadd)", group: "raag" },
  68: { name: "Raag Mali Gaura", group: "raag" },
  69: { name: "Raag Maru", group: "raag" },
  70: { name: "Raag Kedara", group: "raag" },
  71: { name: "Raag Bhairo", group: "raag" },
  72: { name: "Raag Basant", group: "raag" },
  73: { name: "Raag Sarang", group: "raag" },
  74: { name: "Raag Malhar", group: "raag" },
  75: { name: "Raag Kanra", group: "raag" },
  76: { name: "Raag Prabhati", group: "raag" },
  77: { name: "Salok Bhagat Kabir Ji", group: "popular" },
  78: { name: "Salok Sheikh Farid Ji", group: "popular" },
  79: { name: "Savaiye Sri Mukhbak Mahalla 5 (1)", group: "popular" },
  80: { name: "Savaiye Sri Mukhbak Mahalla 5 (2)", group: "popular" },
  81: { name: "Savaiye Mahalle Pehle Ke", group: "popular" },
  82: { name: "Savaiye Mahalle Dooje Ke", group: "popular" },
  83: { name: "Savaiye Mahalle Teeje Ke", group: "popular" },
  84: { name: "Savaiye Mahalle Chauthe Ke", group: "popular" },
  85: { name: "Savaiye Mahalle Panjve Ke", group: "popular" },
  86: { name: "Sri Raag Ki Vaar Mahalla 4", group: "vaar" },
  87: { name: "Vaar Majh Ki", group: "vaar" },
  88: { name: "Gauri Ki Vaar Mahalla 4", group: "vaar" },
  89: { name: "Gauri Ki Vaar Mahalla 5", group: "vaar" },
  90: { name: "Asa Ki Vaar", group: "vaar" },
  91: { name: "Gujri Ki Vaar Mahalla 3", group: "vaar" },
  92: { name: "Gujri Ki Vaar Mahalla 5", group: "vaar" },
  93: { name: "Bihagre Ki Vaar Mahalla 4", group: "vaar" },
  94: { name: "Vadhans Ki Vaar Mahalla 4", group: "vaar" },
  95: { name: "Sorath Ki Vaar Mahalla 4", group: "vaar" },
  96: { name: "Jaitsri Ki Vaar", group: "vaar" },
  97: { name: "Vaar Suhi Ki", group: "vaar" },
  98: { name: "Bilaval Ki Vaar Mahalla 4", group: "vaar" },
  99: { name: "Ramkali Ki Vaar Mahalla 3", group: "vaar" },
  100: { name: "Ramkali Ki Vaar Mahalla 5", group: "vaar" },
  101: { name: "Ramkali Ki Vaar (Rai Balwand & Satta)", group: "vaar" },
  102: { name: "Maru Vaar Mahalla 3", group: "vaar" },
  103: { name: "Maru Vaar Mahalla 5 Dakhne", group: "vaar" },
  104: { name: "Basant Ki Vaar", group: "vaar" },
  105: { name: "Sarang Ki Vaar Mahalla 4", group: "vaar" },
  106: { name: "Vaar Malhar Ki Mahalla 1", group: "vaar" },
  107: { name: "Kanre Ki Vaar Mahalla 4", group: "vaar" },
};

export const GROUPS = [
  { id: "nitnem",  label: "Nitnem" },
  { id: "popular", label: "Popular" },
  { id: "vaar",    label: "Vaars" },
  { id: "raag",    label: "Raags" },
];

/** The English name as written, falling back to the catalogue if unknown. */
export const baniName = (bani) =>
  (BANI_INFO[bani.bani_id] && BANI_INFO[bani.bani_id].name) ||
  bani.english || "";

export const baniGroup = (bani) =>
  (BANI_INFO[bani.bani_id] && BANI_INFO[bani.bani_id].group) || "popular";
